version: '3.8'

services:
  react-app:
    build:
      dockerfile: Dockerfile
    networks:
      - huisterapi_default
    ports:
      - "5173:5173"

networks:
  huisterapi_default:
    external: true